services:
  ffmpeg:
    build:
      context: ffmpeg
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - hls_data:/tmp/hls
    command: >
      ffmpeg
      -f v4l2
      -framerate 30
      -i /dev/video0
      -vf "scale=1920:1080,format=yuv420p"
      -c:v libx264
      -preset superfast
      -b:v 5000k
      -maxrate 5000k
      -bufsize 10000k
      -crf 18
      -g 50
      -r 30
      -an
      -hls_time 10
      -hls_segment_filename "/tmp/hls/segment_%03d.ts"
      -hls_list_size 250
      -hls_flags delete_segments
      -f hls /tmp/hls/stream.m3u8
  nginx:
    build:
      context: nginx
    ports:
      - "443:443"
    volumes:
      - hls_data:/tmp/hls

volumes:
  hls_data:

